import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property <int> counter: 42;
    callback request-increase-value();
    callback request-decrise-value();
    callback request-set-value-100();
    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }

        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }

        Button {
            text: "Decrise value";
            clicked => {
                root.request-decrise-value();
            }
        }

        Button {
            text: "Set value to 100";
            clicked => {
                root.request-set-value-100();
            }
        }
    }
}
